/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILaunchpadNFT, ILaunchpadNFTInterface } from "../ILaunchpadNFT";

const _abi = [
  {
    inputs: [],
    name: "getLaunchpadSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMaxLaunchpadSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "size",
        type: "uint256",
      },
    ],
    name: "mintTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILaunchpadNFT__factory {
  static readonly abi = _abi;
  static createInterface(): ILaunchpadNFTInterface {
    return new utils.Interface(_abi) as ILaunchpadNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILaunchpadNFT {
    return new Contract(address, _abi, signerOrProvider) as ILaunchpadNFT;
  }
}
